### ISSUE TITLE
Format of transaction reference id is changing - does this affect our implementation

### ISSUE THREAD

**Issue by vohmar** [internetee/lhv#6]
Announcement from LHV:

> We are soon changing the format of transaction reference in payment and account info messages. So far it has also included date information, but will be replaced with a random string of 32 characters. It impacts AcctSvcrRef tags in PAIN.002, CAMT.053 and CAMT.054 messages.
> 
> Old format example: 202009081020678875-016192782
> New format example: D9C8845A4BBAEA11910E00155DBDB777
> 
> Please make sure this change does not impact your integration. In essence it is a unique ID for any payment on your accounts and generated by LHV. Actually it is not stated in the specification that it should contain any date values or any other relevant information. However we want to make sure that you haven't added any additional logic on top of it on your own initiative and your API integration is not impacted by this small change.
> 
> Change is planned for release on 2020.10.14 (in one month).

LHV connect updates are trackable here: https://partners.lhv.ee/en/connect/#latest-updates

**Comment by yulgolem** [comment]
Seems like we are not affected by that.
